# Site settings
title: CollegiumV
description: > # this means to ignore newlines until "baseurl:"
    The Collegium V Honors College provides a four-year honors
    experience that encourages intellectually creative, inquisitive, 
    and highly motivated students to extend their educational 
    experience beyond the scope of the traditional undergraduate 
    curriculum.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://collegiumv.org" # the base hostname & protocol for your site
github_username: collegiumv 

paginate: 5
paginate_path: "/news/p:num"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
