# Site settings
title: Collegium V
description: > # this means to ignore newlines until "baseurl:"
    The Collegium V Honors College provides a four-year honors
    experience that encourages intellectually creative, inquisitive,
    and highly motivated students to extend their educational
    experience beyond the scope of the traditional undergraduate
    curriculum.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://collegiumv.org" # the base hostname & protocol for your site
github_username: collegiumv
facebook_group: 337454759652070
permalink: pretty

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/news/p:num"
excerpt_separator: <!--more-->

markdown: kramdown

# announcement: >
#         <h5>Lounge Maintenance Tonight</h5>
#         <p>Printing in the lounge may be unavailable from 2AM to 4AM tonight while we perform maintenance on the print server</p>
#         <a href="#">Where can I print?</a>
